# IV.12.8(b)
Методом простой итерации найти ширину функции $f(x) = x e^{-x^2}, \; x \geq 0$ на полувысоте с точностью $\varepsilon = 10^{-3}$\

Найдем высоту $h$. $f'(x) = (1 - 2x^2) e^{-x^2} = 0$. Отсюда $x_0 = \dfrac{1}{\sqrt{2}}$\
$h = f(x_0)$\

Ищем корни $x_1$ и $x_2$ уравнения $g(x) = f(x) - f(x_0)/2$\
$l = |x_2 - x_1| - $ искомая ширина функции на полувысоте\
Чтобы точность была $\varepsilon$, корни $x_1$ и $x_2$ нужно находить с точностью не хуже $\varepsilon/2$

In [29]:
from math import exp, sqrt, log

In [30]:
eps = 10 ** (-3)

In [31]:
def f(x):
    return x * exp(- x ** 2)

x_0 = 1 / sqrt(2)
C = f(x_0) / 2

def g(x):
    return f(x) - C

## Локализация корней

In [32]:
for i in range(3):
    print(f"g({i}) = {g(i):.3f}")
print(f"g({0.9}) = {g(0.9):.3f}")

g(0) = -0.214
g(1) = 0.153
g(2) = -0.178
g(0.9) = 0.186


Итого $x_1 \in [0; 0.9]; \; x_2 \in [1; 2]$

## Уточнение кореней

1. Отрезок $x_1 \in [0; 0.9]$\
$g(x) = f(x) - f(x_0)/2 = x e^{-x^2} - C = 0 \; \Rightarrow \; x^{n+1} = \varphi(x^n) = Ce^{(x^n)^2}$. Графически определим, что $|\varphi ' (x)| < 1$ при $x \in [0; 0.9] \; \Rightarrow$ метод сходится

Условие остановки выбрано $|x^{n+1} - x^n| \leq \varepsilon / 10$, чтобы точно зафиксировать 3 знака после запятой

In [33]:
x_1 = 0.45
x_1_cur = C * exp(x_1 ** 2)
i = 1
print(f"x^{i} = {x_1_cur:.5f}")
while abs(x_1_cur - x_1) > eps / 10:
    i += 1
    x_1 = x_1_cur
    x_1_cur = C * exp(x_1 ** 2)
    print(f"x^{i} = {x_1_cur:.5f}")

x^1 = 0.26257
x^2 = 0.22975
x^3 = 0.22606
x^4 = 0.22568
x^5 = 0.22565


2. Отрезок $x_2 \in [1; 2]$\
$g(x) = f(x) - f(x_0)/2 = x e^{-x^2} - C = 0 \; \Rightarrow \; x^{n+1} = \varphi(x^n) = \sqrt{-\ln{\dfrac{C}{x}}}$. На отрезке функция $\varphi(x)$ определена и $|\varphi '(x)| < 1 \; \Rightarrow$ метод сходится

Условие остановки выбрано $|x^{n+1} - x^n| \leq \varepsilon / 10$, чтобы точно зафиксировать 3 знака после запятой

In [35]:
x_2 = 1.5
x_2_cur = sqrt(-log(C/x_2))
i = 1
print(f"x^{i} = {x_2_cur:.5f}")
while abs(x_2_cur - x_2) > eps / 10:
    i += 1
    x_2 = x_2_cur
    x_2_cur = sqrt(-log(C/x_2))
    print(f"x^{i} = {x_2_cur:.5f}")

x^1 = 1.39470
x^2 = 1.36836
x^3 = 1.36137
x^4 = 1.35949
x^5 = 1.35898
x^6 = 1.35884
x^7 = 1.35881


Итого: $x_1 = 0.2256, x_2 = 1.3588$. Значит искомая ширина функции на полувысоте\
**$l = x_2 - x_1 = 1.1332$**